### ISSUE TITLE
Namespace refactoring

### ISSUE THREAD

**Issue by kMutagene** [plotly/Dash.NET#11]
- [x] The HTML DSL is too verbose. Instead of `Button.button` users should be able to just use `button` (it is now Html.button)
- [ ] Change Callback argument order to mirror python behaviour
- [ ] use a single overloaded method for creating callbacks
